-   id: sync-rye-pre-commit
    name: Sync rye and pre commit
    description: Sync rye and pre commit
    language: python
    language_version: "3.12"
    entry: "sync_rye_pre_commit"
    minimum_pre_commit_version: "2.9.2"